services:
  market-data-service:
    build:
      context: .
      dockerfile: market-data-service/Dockerfile
    container_name: market-data-service
    ports:
      - "8001:8001"
    restart: unless-stopped
  pricing-service:
    build:
      context: .
      dockerfile: pricing-service/Dockerfile
    environment:
      - STREAM_URL=http://market-data-service:8001/stream
    container_name: pricing-service
    ports:
      - "8002:8002"
    restart: unless-stopped
    depends_on:
      - market-data-service
  monitoring-service:
    build:
      context: .
      dockerfile: monitoring-service/Dockerfile
    environment:
      - MARKET_DATA_SERVICE_HEALTHCHECK_URL=http://market-data-service:8001/health
      - PRICING_SERVICE_HEALTHCHECK_URL=http://pricing-service:8002/health
    container_name: monitoring-service
    ports:
      - "8003:8003"
    restart: unless-stopped