from shared.config import TICK_INTERVAL_MS, SNAPSHOT_INTERVAL_MS, LOG_LEVEL

SERVICE_NAME = "market-data-service"
HOST = "0.0.0.0"
PORT = 8001

SNAPSHOT_INTERVAL_SECONDS = SNAPSHOT_INTERVAL_MS / 1000.0
