from desk_runtime.config import env_float, env_int, env_str
from desk_pricing.risk import MINIMUM_OBSERVATIONS

SERVICE_NAME = "pricing-service"
PORT = 8002

TRADE_REFRESH_SECONDS = 2
VALUATION_WRITE_INTERVAL_SECONDS = env_int("VALUATION_WRITE_INTERVAL_SECONDS", 60)
VALUATION_STREAM_QUEUE_SIZE = 5000

MARKET_DATA_STREAM_URL = env_str("MARKET_DATA_STREAM_URL")

BOOK_RISK_WINDOW = env_int("BOOK_RISK_WINDOW", 100)
BOOK_RISK_MINIMUM_OBSERVATIONS = env_int("BOOK_RISK_MINIMUM_OBSERVATIONS", MINIMUM_OBSERVATIONS)
BOOK_CAPITAL_BASE = env_float("BOOK_CAPITAL_BASE", 1_000_000.0)
PORTFOLIO_CAPITAL_BASE = env_float("PORTFOLIO_CAPITAL_BASE")
