from shared.config import env_int, env_str

SERVICE_NAME = "market-data-service"
PORT = 8001

FINNHUB_API_KEY = env_str("FINNHUB_API_KEY")
FINNHUB_TIER1_POLL_SECONDS = env_int("FINNHUB_TIER1_POLL_SECONDS", 15)
FINNHUB_TIER2_POLL_SECONDS = env_int("FINNHUB_TIER2_POLL_SECONDS", 60)
FINNHUB_CLOSED_POLL_SECONDS = env_int("FINNHUB_CLOSED_POLL_SECONDS", 300)
FINNHUB_BUDGET_PER_MINUTE = env_int("FINNHUB_BUDGET_PER_MINUTE", 48)
SNAPSHOT_RETENTION_DAYS = env_int("SNAPSHOT_RETENTION_DAYS", 90)

REQUEST_TIMEOUT_SECONDS = 10
ACTIVE_SET_REFRESH_SECONDS = 15
MARKET_STATUS_REFRESH_SECONDS = 600
RETENTION_SWEEP_INTERVAL_SECONDS = 24 * 3600
FRESHNESS_THRESHOLD_MULTIPLIER = 3
RATE_LIMIT_DEFAULT_COOLDOWN_SECONDS = 60
AUTH_FAILURE_COOLDOWN_SECONDS = 300
TRANSIENT_ERROR_BACKOFF_SECONDS = 10
