import math

from shared.config import env_int, env_str


def _symbol_list(name, default):
    return tuple(
        symbol.strip().upper()
        for symbol in env_str(name, default).split(",")
        if symbol.strip()
    )

SERVICE_NAME = "market-data-service"
PORT = 8001

FINNHUB_API_KEY = env_str("FINNHUB_API_KEY")
FINNHUB_TIER1_POLL_SECONDS = env_int("FINNHUB_TIER1_POLL_SECONDS", 15)
FINNHUB_TIER2_POLL_SECONDS = env_int("FINNHUB_TIER2_POLL_SECONDS", 60)
FINNHUB_CLOSED_POLL_SECONDS = env_int("FINNHUB_CLOSED_POLL_SECONDS", 300)
PROVIDER_BUDGET_USAGE_PERCENT = env_int("PROVIDER_BUDGET_USAGE_PERCENT", 90)
PROVIDER_ACTIVE_WINDOW_HOURS = env_int("PROVIDER_ACTIVE_WINDOW_HOURS", 12)
FINNHUB_PROVIDER_LIMIT_PER_MINUTE = env_int("FINNHUB_PROVIDER_LIMIT_PER_MINUTE", 60)
TWELVE_DATA_API_KEY = env_str("TWELVE_DATA_API_KEY")
TWELVE_DATA_POLL_SECONDS = env_int("TWELVE_DATA_POLL_SECONDS", 900)
TWELVE_DATA_PROVIDER_LIMIT_PER_DAY = env_int("TWELVE_DATA_PROVIDER_LIMIT_PER_DAY", 800)
TWELVE_DATA_PROVIDER_LIMIT_PER_MINUTE = env_int(
    "TWELVE_DATA_PROVIDER_LIMIT_PER_MINUTE", 8
)
SNAPSHOT_RETENTION_DAYS = env_int("SNAPSHOT_RETENTION_DAYS", 90)
MAX_ACTIVE_SYMBOLS = env_int("MAX_ACTIVE_SYMBOLS", 25)
NBP_REFERENCE_SYMBOLS = _symbol_list("NBP_REFERENCE_SYMBOLS", "EURPLN,USDPLN,XAUPLN_G")
ECB_REFERENCE_SYMBOLS = _symbol_list("ECB_REFERENCE_SYMBOLS", "EURUSD,EURPLN")

if not 1 <= PROVIDER_BUDGET_USAGE_PERCENT <= 100:
    raise ValueError("PROVIDER_BUDGET_USAGE_PERCENT must be between 1 and 100")
if not 1 <= PROVIDER_ACTIVE_WINDOW_HOURS <= 24:
    raise ValueError("PROVIDER_ACTIVE_WINDOW_HOURS must be between 1 and 24")


def _safe_budget(provider_limit):
    if provider_limit < 1:
        raise ValueError("provider limits must be positive")
    return max(1, math.floor(provider_limit * PROVIDER_BUDGET_USAGE_PERCENT / 100))


FINNHUB_BUDGET_PER_MINUTE = _safe_budget(FINNHUB_PROVIDER_LIMIT_PER_MINUTE)
TWELVE_DATA_DAILY_BUDGET = _safe_budget(TWELVE_DATA_PROVIDER_LIMIT_PER_DAY)
TWELVE_DATA_BUDGET_PER_MINUTE = _safe_budget(TWELVE_DATA_PROVIDER_LIMIT_PER_MINUTE)
PROVIDER_ACTIVE_WINDOW_SECONDS = PROVIDER_ACTIVE_WINDOW_HOURS * 3600

REQUEST_TIMEOUT_SECONDS = 10
ACTIVE_SET_REFRESH_SECONDS = 15
MARKET_STATUS_REFRESH_SECONDS = 600
RETENTION_SWEEP_INTERVAL_SECONDS = 24 * 3600
FRESHNESS_THRESHOLD_MULTIPLIER = 3
PROVIDER_CLOCK_LAG_SECONDS = 60
RATE_LIMIT_DEFAULT_COOLDOWN_SECONDS = 60
AUTH_FAILURE_COOLDOWN_SECONDS = 300
TRANSIENT_ERROR_BACKOFF_SECONDS = 10
SYMBOL_SEARCH_CACHE_SECONDS = 600
SYMBOL_SEARCH_RESULT_LIMIT = 10

NBP_GOLD_SYMBOL = "XAUPLN_G"
NBP_WINDOW_START = (11, 45)
NBP_WINDOW_END = (12, 20)
ECB_WINDOW_START = (15, 55)
ECB_WINDOW_END = (16, 45)
REFERENCE_WINDOW_RETRY_SECONDS = 300
REFERENCE_CONFIRM_SECONDS = 3600
REFERENCE_SET_REFRESH_SECONDS = 60
REFERENCE_LOOP_SLEEP_SECONDS = 15
REFERENCE_PUBLICATION_GRACE_SECONDS = 4 * 3600
