from shared.config import (
    LOG_LEVEL,
    TRADE_ACTION_SERVICE_URL,
    BOOKS_SERVICE_URL,
    MARKET_DATA_SNAPSHOT_URL,
    TRADE_GENERATION_INTERVAL_MS,
    CLOSE_PROBABILITY,
)

SERVICE_NAME = "trade-generation-service"
HOST = "0.0.0.0"
PORT = 8007

TRADE_ACTIONS_URL = f"{TRADE_ACTION_SERVICE_URL}/trade-actions"
BOOKS_URL = f"{BOOKS_SERVICE_URL}/books"
SNAPSHOT_URL = MARKET_DATA_SNAPSHOT_URL
