from shared.config import env_float, env_int, env_str
from shared.pricing_math import MINIMUM_OBSERVATIONS
from shared.providers import FINNHUB

SERVICE_NAME = "pricing-service"
PORT = 8002

TRADE_REFRESH_SECONDS = 2
VALUATION_STREAM_QUEUE_SIZE = 5000

DEFAULT_QUOTE_PROVIDER = FINNHUB

MARKET_DATA_STREAM_URL = env_str("MARKET_DATA_STREAM_URL")

BOOK_RISK_WINDOW = env_int("BOOK_RISK_WINDOW", 100)
BOOK_RISK_MINIMUM_OBSERVATIONS = env_int("BOOK_RISK_MINIMUM_OBSERVATIONS", MINIMUM_OBSERVATIONS)
BOOK_CAPITAL_BASE = env_float("BOOK_CAPITAL_BASE", 1_000_000.0)
PORTFOLIO_CAPITAL_BASE = env_float("PORTFOLIO_CAPITAL_BASE")
