export const BOOK_SUMMARY_POLL_INTERVAL_MS = 5000

export const BOOK_ASSET_CLASSES = ['BOND', 'COMMODITY', 'EQUITY', 'FUTURES', 'FX']

export const BOOK_NAME_MAX_LENGTH = 60
export const BOOK_DESCRIPTION_MAX_LENGTH = 200
