import os

DATABASE_URL = os.environ.get("DATABASE_URL")

MARKET_DATA_STREAM_URL = os.environ.get("MARKET_DATA_STREAM_URL")
MARKET_DATA_SNAPSHOT_URL = os.environ.get("MARKET_DATA_SNAPSHOT_URL")
VALUATION_STREAM_URL = os.environ.get("VALUATION_STREAM_URL")
TRADE_ACTION_SERVICE_URL = os.environ.get("TRADE_ACTION_SERVICE_URL")
BOOKS_SERVICE_URL = os.environ.get("BOOKS_SERVICE_URL")

MARKET_DATA_SERVICE_HEALTHCHECK_URL = os.environ.get("MARKET_DATA_SERVICE_HEALTHCHECK_URL")
PRICING_SERVICE_HEALTHCHECK_URL = os.environ.get("PRICING_SERVICE_HEALTHCHECK_URL")
MONITORING_SERVICE_HEALTHCHECK_URL = os.environ.get("MONITORING_SERVICE_HEALTHCHECK_URL")
BOOKS_SERVICE_HEALTHCHECK_URL = os.environ.get("BOOKS_SERVICE_HEALTHCHECK_URL")
TRADE_ACTION_SERVICE_HEALTHCHECK_URL = os.environ.get("TRADE_ACTION_SERVICE_HEALTHCHECK_URL")
TRADE_GENERATION_SERVICE_HEALTHCHECK_URL = os.environ.get("TRADE_GENERATION_SERVICE_HEALTHCHECK_URL")
BLOTTER_SERVICE_HEALTHCHECK_URL = os.environ.get("BLOTTER_SERVICE_HEALTHCHECK_URL")

TICK_INTERVAL_MS = int(os.environ.get("TICK_INTERVAL_MS"))
SNAPSHOT_INTERVAL_MS = int(os.environ.get("SNAPSHOT_INTERVAL_MS"))
TRADE_GENERATION_INTERVAL_MS = int(os.environ.get("TRADE_GENERATION_INTERVAL_MS"))
TARGET_OPEN_TRADES = int(os.environ.get("TARGET_OPEN_TRADES", "300"))
TARGET_NOTIONAL = float(os.environ.get("TARGET_NOTIONAL", "100000"))

LOG_LEVEL = os.environ.get("LOG_LEVEL")
