from shared.config import env_float, env_int
from shared.providers import QUOTE_PROVIDERS

SERVICE_NAME = "trade-action-service"
PORT = 8008

QUOTE_PROVIDER_CHOICES = QUOTE_PROVIDERS

TRADE_PRICE_TOLERANCE_PCT = env_float("TRADE_PRICE_TOLERANCE_PCT", 1.0)
TRADE_ACTION_QUEUE_SIZE = env_int("TRADE_ACTION_QUEUE_SIZE", 1000)
TRADE_ACTION_BATCH_SIZE = env_int("TRADE_ACTION_BATCH_SIZE", 100)
