"""new features

Revision ID: 6e75e5926e2e
Revises: 243f3be5acf5
Create Date: 2026-06-02 22:29:27.379075

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6e75e5926e2e'
down_revision: Union[str, Sequence[str], None] = '243f3be5acf5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'books', ['name'])
    op.add_column('trades', sa.Column('valuation_finalized', sa.Boolean(), server_default='FALSE', nullable=False))
    op.create_unique_constraint(None, 'trades', ['client_request_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'trades', type_='unique')
    op.drop_column('trades', 'valuation_finalized')
    op.drop_constraint(None, 'books', type_='unique')
    # ### end Alembic commands ###
