"""indexes

Revision ID: d19af2df2449
Revises: 6e75e5926e2e
Create Date: 2026-06-08 21:05:51.302404

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd19af2df2449'
down_revision: Union[str, Sequence[str], None] = '6e75e5926e2e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_audit_logs_entity_id', 'audit_logs', ['entity_id'], unique=False)
    op.create_index('ix_trades_asset_class', 'trades', ['asset_class'], unique=False)
    op.create_index('ix_trades_book_id', 'trades', ['book_id'], unique=False)
    op.create_index('ix_trades_status', 'trades', ['status'], unique=False)
    op.create_index('ix_trades_symbol', 'trades', ['symbol'], unique=False)
    op.create_index('ix_valuations_trade_id_time', 'valuations', ['trade_id', 'valuation_time'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_valuations_trade_id_time', table_name='valuations')
    op.drop_index('ix_trades_symbol', table_name='trades')
    op.drop_index('ix_trades_status', table_name='trades')
    op.drop_index('ix_trades_book_id', table_name='trades')
    op.drop_index('ix_trades_asset_class', table_name='trades')
    op.drop_index('ix_audit_logs_entity_id', table_name='audit_logs')
    # ### end Alembic commands ###
